### ISSUE TITLE
Using the {{include.___}} variable

### ISSUE THREAD

**Issue by JuliaProkipcak** [JuliaProkipcak/ecommerce-pattern-library#2]
Hi Thomas,
I am following the lesson titled "building pages with patterns" and I'm a little confused about how to use the variable. I can see how to use it for regular image tags and svgs but I used a background image tag for my main banner, do the variable tags work the same in css where the image link is?
@thomasjbradley

**Comment by thomasjbradley** [comment]
It doesn’t work directly in CSS. We generally have to stick to using it in HTML.

So, you’ll need to write CSS *within* HTML, say this `<div>` is the tag that has a CSS background image:

```html
<div style="background-image:url({{include.img}})">

</div>
```

Notice we have a new HTML attribute: `style` this is how you can write CSS in HTML. It’s generally not a good practice, but makes sense in this situation.
